name = "transcription-worker"
main = "src/index.js"
compatibility_date = "2024-07-24"
workers_dev = true

[ai]
binding = "AI"

[[kv_namespaces]]
id = "9414340d2dd04e42afdcfadef9dadc1d"
binding = "TRANSCRIPTION_JOBS"
